Improves port setting
RockefellerArchiveCenter/nebula pull request #6
Opened 2021-11-18 15:00 UTC by helrond

Simplifies port setting for local development as well as Travis CI.
- Uses an $APPLICATION_PORT variable in Travis CI to set the port on which the application is expected to run. The Docker Compose file will pick up that variable and pass it along to the container, where is is used by entrypoint.sh.
- For local development, this environment variable will not be available, so there are default values in the Docker Compose file, which again are passed along to the container.

To run on a different port locally, you will simply need to change the default values in the Compose file. 
To update the port on which the application is deployed, either change the value in .travis.yml or, if applicable, the value assigned to $APPLICATION_PORT in the Travis settings UI.

2021-11-18 17:00 UTC, HaSistrunk approved these changes

2021-11-19 15:04 UTC, bonniegee requested changes
Might be worth adding a bullet point about changing the port for local development to "Other things you'll want to do" in the README?

2021-11-19 15:09 UTC, p-galligan approved these changes

2021-11-19 20:36 UTC, bonniegee approved these changes

2021-11-19 20:54 UTC, merged